#include "Adafruit_AVRProg.h"

#define UPDI_BREAK 0x00

#define UPDI_LDS	0x00
#define UPDI_STS	0x40
#define UPDI_LD		0x20
#define UPDI_ST		0x60
#define UPDI_LDCS	0x80
#define UPDI_STCS	0xC0
#define UPDI_REPEAT 0xA0
#define UPDI_KEY	0xE0

#define UPDI_PTR		 0x00
#define UPDI_PTR_INC	 0x04
#define UPDI_PTR_ADDRESS 0x08

#define UPDI_ADDRESS_8	0x00
#define UPDI_ADDRESS_16 0x04

#define UPDI_DATA_8	 0x00
#define UPDI_DATA_16 0x01

#define UPDI_KEY_SIB 0x04
#define UPDI_KEY_KEY 0x00

#define UPDI_KEY_64	 0x00
#define UPDI_KEY_128 0x01

#define UPDI_SIB_8BYTES	 UPDI_KEY_64
#define UPDI_SIB_16BYTES UPDI_KEY_128

#define UPDI_REPEAT_BYTE 0x00
#define UPDI_REPEAT_WORD 0x01

#define UPDI_PHY_SYNC 0x55
#define UPDI_PHY_ACK  0x40

#define UPDI_MAX_REPEAT_SIZE 0xFF

//CS and ASI Register Address map
#define UPDI_CS_STATUSA		0x00
#define UPDI_CS_STATUSB		0x01
#define UPDI_CS_CTRLA		0x02
#define UPDI_CS_CTRLB		0x03
#define UPDI_ASI_KEY_STATUS 0x07
#define UPDI_ASI_RESET_REQ	0x08
#define UPDI_ASI_CTRLA		0x09
#define UPDI_ASI_SYS_CTRLA	0x0A
#define UPDI_ASI_SYS_STATUS 0x0B
#define UPDI_ASI_CRC_STATUS 0x0C

#define UPDI_CTRLA_IBDLY_BIT	7
#define UPDI_CTRLA_RSD_BIT		3
#define UPDI_CTRLB_CCDETDIS_BIT 3
#define UPDI_CTRLB_UPDIDIS_BIT	2

#define UPDI_KEY_NVM		   "NVMProg "
#define UPDI_KEY_CHIPERASE	   "NVMErase"
#define UPDI_KEY_USERROW_WRITE "NVMUs&te"

#define UPDI_ASI_STATUSA_REVID 4
#define UPDI_ASI_STATUSB_PESIG 0

#define UPDI_ASI_KEY_STATUS_CHIPERASE 3
#define UPDI_ASI_KEY_STATUS_NVMPROG	  4
#define UPDI_ASI_KEY_STATUS_UROWWRITE 5

#define UPDI_ASI_SYS_STATUS_RSTSYS	   5
#define UPDI_ASI_SYS_STATUS_INSLEEP	   4
#define UPDI_ASI_SYS_STATUS_NVMPROG	   3
#define UPDI_ASI_SYS_STATUS_UROWPROG   2
#define UPDI_ASI_SYS_STATUS_LOCKSTATUS 0

#define UPDI_ASI_SYS_CTRLA_UROWupdi_write_FINAL 1
#define UPDI_ASI_SYS_CTRLA_CLKREQ				0

#define UPDI_RESET_REQ_VALUE 0x59

//FLASH CONTROLLER
#define UPDI_NVMCTRL_CTRLA	  0x00
#define UPDI_NVMCTRL_CTRLB	  0x01
#define UPDI_NVMCTRL_STATUS	  0x02
#define UPDI_NVMCTRL_INTCTRL  0x03
#define UPDI_NVMCTRL_INTFLAGS 0x04
#define UPDI_NVMCTRL_DATAL	  0x06
#define UPDI_NVMCTRL_DATAH	  0x07
#define UPDI_NVMCTRL_ADDRL	  0x08
#define UPDI_NVMCTRL_ADDRH	  0x09

//CTRLA
#define UPDI_NVMCTRL_CTRLA_NOP					 0x00
#define UPDI_NVMCTRL_CTRLA_updi_write_PAGE		 0x01
#define UPDI_NVMCTRL_CTRLA_ERASE_PAGE			 0x02
#define UPDI_NVMCTRL_CTRLA_ERASE_updi_write_PAGE 0x03
#define UPDI_NVMCTRL_CTRLA_PAGE_BUFFER_CLR		 0x04
#define UPDI_NVMCTRL_CTRLA_updi_erase_chip		 0x05
#define UPDI_NVMCTRL_CTRLA_ERASE_EEPROM			 0x06
#define UPDI_NVMCTRL_CTRLA_UPDI_WRITE_FUSE		 0x07

#define UPDI_NVM_STATUS_UPDI_WRITE_ERROR 2
#define UPDI_NVM_STATUS_EEPROM_BUSY		 1
#define UPDI_NVM_STATUS_FLASH_BUSY		 0

#define UPDI_MAX_FILENAME_LEN 256
#define AVR_SYSCFG_ADDRESS	  0x0F00
#define AVR_OCD_ADDRESS		  0x0F80
#define AVR_NVM_ADDRESS		  0x1000
#define AVR_SIG_ADDRESS		  0x1100
#define AVR_FUSES_ADDRESS	  0x1280
#define AVR_USERSIG_ADDRESS	  0x1300
#define AVR_EEPROM_ADDR		  0x1400
#define AVR_FLASH_ADDR		  // varies with chip size
#define AVR_UID_LENGTH		  10

// FUSE definitions
#define AVR_FUSE_UNINITIALIZED 0xFF	// TODO need to find a value that is guaranteed to never be used
#define AVR_NUM_FUSES	 11 // 3 fuses are marked 'reserved': the 4th, 5th, and 10th (0-based #3, #4, and #9)
#define AVR_FUSE_BASE	 0x1280
#define AVR_FUSE_WDTCFG	 0x1280 // watch dog timer
#define AVR_FUSE_BODCFG	 0x1281 // brown out detection
#define AVR_FUSE_OSCCFG	 0x1282 // oscillator frequency
#define AVR_FUSE_RESV3	 0x1283 // must be 0xFF
#define AVR_FUSE_RESV4	 0x1284
#define AVR_FUSE_SYSCFG0 0x1285
#define AVR_FUSE_SYSCFG1 0x1286
#define AVR_FUSE_APPEND	 0x1287
#define AVR_FUSE_BOOTEND 0x1288
#define AVR_FUSE_RESV9	 0x1289
#define AVR_FUSE_LOCK	 0x128A

